spring.datasource.url=jdbc:h2:file:${project.dir:.}/db/data;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root