create TABLE IF NOT EXISTS "posts" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    text VARCHAR(7000) NOT NULL,
    likes_count INTEGER NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "post_images" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL,
    image_data BYTEA NOT NULL,
    CONSTRAINT uq_post_images_post_id UNIQUE (post_id),
    CONSTRAINT fk_post_images_post_id_posts_id FOREIGN KEY (post_id)
        REFERENCES "posts"(id) ON DELETE CASCADE
);