create TABLE IF NOT EXISTS "posts" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    text VARCHAR(7000) NOT NULL,
    likes_count BIGINT NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "post_images" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL,
    image_data BYTEA NOT NULL,
    CONSTRAINT pk_post_images PRIMARY KEY (id),
    CONSTRAINT uq_post_images_post_id UNIQUE (post_id),
    CONSTRAINT fk_post_images_post_id_posts_id FOREIGN KEY (post_id)
        REFERENCES "posts"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "post_comments" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL,
    text VARCHAR(7000) NOT NULL,
    CONSTRAINT pk_post_comments PRIMARY KEY (id),
    CONSTRAINT fk_post_comments_post_id_posts_id FOREIGN KEY (post_id)
        REFERENCES "posts"(id) ON DELETE CASCADE
);

create TABLE IF NOT EXISTS "tags" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tag_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uq_tags_tag_name UNIQUE (tag_name)
);

CREATE TABLE IF NOT EXISTS "post_tags" (
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tags_post_id_posts_id FOREIGN KEY (post_id)
        REFERENCES "posts"(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_tags_tag_id_tags_id FOREIGN KEY (tag_id)
        REFERENCES "tags"(id)
);